{% set name = "dtool_utils" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool_utils/dtool_utils-{{ version }}.tar.gz
  sha256: e86dba9151214a3e9d15110e76ba03fd258d880e286eb074392ff5c4dd0bc3a6
  patches:
    - setup.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dtoolcore >=3.0.0
    - python >={{ python_min }}
    - ruamel.yaml

test:
  imports:
    - dtool_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
  
about:
  home: https://pypi.org/project/dtool-utils/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: 'Dtool utility functions and classes'
  description: |
    Dtool utility functions and classes
  doc_url: https://pypi.org/project/dtool-utils/
  dev_url: https://pypi.org/project/dtool-utils/

extra:
  recipe-maintainers:
    - jan-janssen
